const schema = require("./schema");

module.exports = {
  ack: new schema.Ack(),
  addOn: new schema.AddOn(),
  address: new schema.Address(),
  agent: new schema.Agent(),
  authorization: new schema.Authorization(),
  billing: new schema.Billing(),
  cancellation: new schema.Cancellation(),
  city: new schema.City(),
  contact: new schema.Contact(),
  credential: new schema.Credential(),
  decimalValue: new schema.DecimalValue(),
  descriptor: new schema.Descriptor(),
  duration: new schema.Duration(),
  fee: new schema.Fee(),
  fulfillmentState: new schema.FulfillmentState(),
  image: new schema.Image(),
  language: new schema.Language(),
  mediaFile: new schema.MediaFile(),
  option: new schema.Option(),
  organization: new schema.Organization(),
  person: new schema.Person(),
  price: new schema.Price(),
  rating: new schema.Rating(),
  schedule: new schema.Schedule(),
  skill: new schema.Skill(),
  state: new schema.State(),
  tag: new schema.Tag(),
  tagGroup: new schema.TagGroup(),
  time: new schema.Time(),
};
